use ski_resort_db;

CREATE TABLE Client(
	id INT PRIMARY KEY IDENTITY,
	LastName NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	Patronymic NVARCHAR(50) NOT NULL,
	PassportSeries INT,
	PassportNumber INT,
	Birthday DATE,
	Address NVARCHAR(100),
	Email NVARCHAR(100),
	Password NVARCHAR(100),
);


CREATE TABLE Employees(
	id INT PRIMARY KEY IDENTITY(101, 1),
	Email NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	Patronymic NVARCHAR(50) NOT NULL,
	Position NVARCHAR(50) NOT NULL,
);

CREATE TABLE LogActivityEmployees(
	EmployeeId INT NOT NULL,
	[Date] DATETIME DEFAULT GETDATE() NOT NULL,
	Success TINYINT DEFAULT 0 NOT NULL,
	FOREIGN KEY (EmployeeId) REFERENCES Employees(id),
	PRIMARY KEY (EmployeeId, [Date]),
);

CREATE TABLE Services(
	Id INT NOT NULL,
	Title NVARCHAR(50) NOT NULL,
	Code NVARCHAR(16) NOT NULL,
	Cost MONEY NOT NULL,
);

ALTER TABLE Services
	ADD PRIMARY KEY (Id);
